name: DID Connect Docs
title: DID Connect Docs
description: This is DID Connect Docs Site, powered by Blocklet Page
github: https://github.com/ArcBlock/did-connect
theme: docs
themeConfig:
  sidebar:
    en:
      - text: Concepts & Workflow
        items:
          - text: Introduction
            link: /intro
          - text: Workflow
            link: /intro/workflow
      - text: Guides
        items:
          - text: Getting Started
            link: /guides/getting-started
          - text: Request User DID
            link: /guides/request-did
          - text: Request User Profile
            link: /guides/request-profile
          - text: Request Verifiable Credential
            link: /guides/request-vc
          - text: Request Asset Proof
            link: /guides/request-asset
          - text: Request Signature
            link: /guides/request-signature
          - text: Request Payment
            link: /guides/request-payment
          - text: Request Agreement
            link: /guides/request-agreement
      - text: Protocol
        link: /protocol
      - text: FAQ
        link: /faq
        items:
          - text: Type cheatsheet
            link: /faq/type-cheatsheet
          - text: Use with typescript
            link: /faq/use-with-typescript
          - text: Framework support
            link: /faq/frameworks-support
    zh:
      - text: 概念和流程
        items:
          - text: 介绍
            link: /intro
          - text: 概念
            link: /concepts
          - text: 流程
            link: /workflow
      - text: 开发者指南
        items:
          - text: 快速上手
            link: /guides/getting-started
          - text: 获取用户DID
            link: /guides/request-did
          - text: 获取用户身份
            link: /guides/request-profile
          - text: 获取可验证声明
            link: /guides/request-vc
          - text: 获取资产声明
            link: /guides/request-asset
          - text: 获取可验证声明
            link: /guides/request-vc
          - text: 获取资产声明
            link: /guides/request-asset
      - text: 协议
        link: /protocol
      - text: FAQ
        link: /faq
        items:
          - text: 在 Typescript 中使用？
            link: /faq/use-with-typescript
          - text: 其他框架的支持？
            link: /faq/other-frameworks-support
